spring:
  profiles:
    active: mysql
  application:
    name: TickTag

url:
  front: http://localhost:3000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
