spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ticktag}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER_NAME:postgres}
    password: ${DATABASE_PASSWORD:753941}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
